# IRIS DATASET 

In [3]:
import math as m
m.sqrt(10)

3.1622776601683795

In [4]:
import numpy as np
l = [1,2,3,4]
a = np.array(l)
c = np.array([9,0,23,45])
print(c)
print(a.dtype)
b = np.zeros((4,5), int)#pay attention to the spelling of zeros
b[0][0] = 19
print(b)
print(b.dtype)

[ 9  0 23 45]
int64
[[19  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
int64


In [5]:
a = np.array([1,5])
b = np.array([2,3])
print(a + b)
print(a - b)
print(a * b)
print(b**2)
print(a.mean())
c = np.array([[1,2,3], [4, 5, 6], [7, 8, 9]])
print(c.size)
print(c.shape)
print(c[1])
print(c[ :, 1:3])

[3 8]
[-1  2]
[ 2 15]
[4 9]
3.0
9
(3, 3)
[4 5 6]
[[2 3]
 [5 6]
 [8 9]]


In [6]:
a = np.array([1,2,3])
b = np.array([2,3,4])
print(((a - a.mean())**2).mean())#variance 
print(np.var(a))#variance using inbuilt function 


0.6666666666666666
0.6666666666666666


In [7]:
import pandas as pd
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')
print(type(iris))

<class 'pandas.core.frame.DataFrame'>


In [8]:
iris.columns = ['sl', 'sw', 'pl', 'pw', 'flower_class']
print(iris.head())
print(iris.shape)
print(iris.dtypes)

    sl   sw   pl   pw flower_class
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
(149, 5)
sl              float64
sw              float64
pl              float64
pw              float64
flower_class     object
dtype: object


In [9]:
iris.describe()

sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [10]:
iris.iloc[3:5, 1:3] = np.nan
print(iris.head())

    sl   sw   pl   pw flower_class
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  NaN  NaN  0.2  Iris-setosa
4  5.4  NaN  NaN  0.4  Iris-setosa


In [11]:
#iris.sw = iris.sw.fillna(1)
iris.sw.fillna(iris.sw.mean(), inplace=True)
print(iris.head())
print(iris.shape)

    sl        sw   pl   pw flower_class
0  4.9  3.000000  1.4  0.2  Iris-setosa
1  4.7  3.200000  1.3  0.2  Iris-setosa
2  4.6  3.100000  1.5  0.2  Iris-setosa
3  5.0  3.041497  NaN  0.2  Iris-setosa
4  5.4  3.041497  NaN  0.4  Iris-setosa
(149, 5)


In [12]:
iris.dropna(inplace=True)
print(iris.head())
print(iris.shape)

    sl   sw   pl   pw flower_class
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa
6  5.0  3.4  1.5  0.2  Iris-setosa
(147, 5)


In [13]:
iris.reset_index(drop = True, inplace=True)
iris.head()

sl   sw   pl   pw flower_class
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  4.6  3.4  1.4  0.3  Iris-setosa
4  5.0  3.4  1.5  0.2  Iris-setosa

In [14]:
iris[iris.flower_class == "Iris-setosa"].describe()

sl         sw         pl         pw
count  47.000000  47.000000  47.000000  47.000000
mean    4.995745   3.402128   1.461702   0.242553
std     0.358716   0.385323   0.175144   0.107834
min     4.300000   2.300000   1.000000   0.100000
25%     4.800000   3.100000   1.400000   0.200000
50%     5.000000   3.400000   1.500000   0.200000
75%     5.200000   3.650000   1.550000   0.300000
max     5.800000   4.400000   1.900000   0.600000

# TITANIC DATASET 

In [26]:
titanic = pd.read_csv('titanic_train.csv')
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [27]:
del titanic['PassengerId']
del titanic['Name']
del titanic['Ticket']
titanic.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [28]:
print(titanic.shape)
print(titanic.isnull().sum())#counts number of NaNs 
a = titanic.Cabin# i get array of the cabins column in dataframe 
a.dropna(inplace=True)
len(a.unique())
del titanic['Cabin']

(891, 9)
Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64


In [29]:
titanic.head()
titanic.shape

(891, 8)

In [30]:
survived = titanic[titanic.Survived == 1]
print(survived.describe())

       Survived      Pclass         Age       SibSp       Parch        Fare
count     342.0  342.000000  290.000000  342.000000  342.000000  342.000000
mean        1.0    1.950292   28.343690    0.473684    0.464912   48.395408
std         0.0    0.863321   14.950952    0.708688    0.771712   66.596998
min         1.0    1.000000    0.420000    0.000000    0.000000    0.000000
25%         1.0    1.000000   19.000000    0.000000    0.000000   12.475000
50%         1.0    2.000000   28.000000    0.000000    0.000000   26.000000
75%         1.0    3.000000   36.000000    1.000000    1.000000   57.000000
max         1.0    3.000000   80.000000    4.000000    5.000000  512.329200


In [31]:
dnsurv = titanic[titanic.Survived == 0]
dnsurv.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count     549.0  549.000000  424.000000  549.000000  549.000000  549.000000
mean        0.0    2.531876   30.626179    0.553734    0.329690   22.117887
std         0.0    0.735805   14.172110    1.288399    0.823166   31.388207
min         0.0    1.000000    1.000000    0.000000    0.000000    0.000000
25%         0.0    2.000000   21.000000    0.000000    0.000000    7.854200
50%         0.0    3.000000   28.000000    0.000000    0.000000   10.500000
75%         0.0    3.000000   39.000000    1.000000    0.000000   26.000000
max         0.0    3.000000   74.000000    8.000000    6.000000  263.000000

In [32]:
titanic.Age.fillna(titanic.Age.mean(), inplace=True)
print(titanic.isnull().sum())
titanic.dropna(inplace=True)
print(titanic.shape)

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64
(889, 8)


In [33]:
titanic.head()
print(titanic.isnull().sum())

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64


In [34]:
def getNumber(s):
    if (s=="male"):
        return 1
    else:
        return 2

titanic['gender'] = titanic['Sex'].apply(getNumber)
del titanic['Sex']
titanic.head()

Survived  Pclass   Age  SibSp  Parch     Fare Embarked  gender
0         0       3  22.0      1      0   7.2500        S       1
1         1       1  38.0      1      0  71.2833        C       2
2         1       3  26.0      0      0   7.9250        S       2
3         1       1  35.0      1      0  53.1000        S       2
4         0       3  35.0      0      0   8.0500        S       1