IRIS DATASET USING GAUSSIAN NAIVE BAYES CLASSIFIER

In [26]:
from sklearn import datasets, naive_bayes
from sklearn.metrics import confusion_matrix
import numpy as np
from sklearn import cross_validation as cv

In [27]:
iris = datasets.load_iris()
iris.data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [28]:
iris.target[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
np.unique(iris.target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))

In [30]:
# we use gaussian naive bayes as the iris data features are continuous 

In [31]:
X_train, X_test, Y_train, Y_test = cv.train_test_split(iris.data, iris.target, test_size=0.3)

In [32]:
clf = naive_bayes.GaussianNB()

In [33]:
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
print(clf.score(X_test, Y_test))

0.9555555555555556


In [34]:
print('Confusion Matrix', end="\n")
print(confusion_matrix(Y_test, Y_pred))


Confusion Matrix
[[11  0  0]
 [ 0 18  1]
 [ 0  1 14]]
